language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm  

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.0
    - php: hhvm

before_script:
  # Composer
  - composer self-update
  - composer install --no-interaction
  - composer validate

  # install testing tools
  - composer require phpunit/phpunit:"^4.8"
  - composer require satooshi/php-coveralls:"dev-master"
  - composer require squizlabs/php_codesniffer:"*"
  - composer require sebastian/phpcpd:"*"
  - composer require phploc/phploc:"*"
  - composer require phpmd/phpmd:"^2.2"
  - composer require pdepend/pdepend:"^2.1"

  # Dirs
  - mkdir -p build/cov
  - mkdir -p build/logs  
  - mkdir -p build/phpunit
  - mkdir -p build/pdepend

  # Update env
  - phpenv rehash

script:
  # PHPUnit tests
  - php vendor/bin/phpunit --configuration phpunit.xml.dist;

after_script:
  # Send to coveralls
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" = "5.5" ]; then
        php vendor/bin/coveralls --verbose;
    fi;'
      
  # Check PSR1,2 src and tests (NOT FOR HipHop !!!)
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" = "5.5" ]; then
        php vendor/bin/phpcs ./src --standard=PSR1,PSR2 --encoding=utf-8 --report=summary -vp | grep "TOTAL\sOF";
    fi;'
  
  # Try to find copy-paste
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" = "5.5" ]; then
        php vendor/bin/phpcpd ./src --no-interaction --verbose;
    fi;'

  # Show code statistic
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" = "5.5" ]; then
        php vendor/bin/phploc ./src --no-interaction --verbose;
    fi;'

  # Show code problems
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" = "5.5" ]; then
        php vendor/bin/phpmd ./src text cleancode     --verbose;
        php vendor/bin/phpmd ./src text codesize      --verbose;
        php vendor/bin/phpmd ./src text controversial --verbose;
        php vendor/bin/phpmd ./src text design        --verbose;
        php vendor/bin/phpmd ./src text naming        --verbose;
        php vendor/bin/phpmd ./src text unusedcode    --verbose;
    fi;'

  # Build pdepend stats
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" = "5.5" ]; then
        php vendor/bin/pdepend
          --summary-xml=build/pdepend/summary.xml
          --jdepend-chart=build/pdepend/jdepend.svg
          --overview-pyramid=build/pdepend/pyramid.svg ./src --verbose;
    fi;'

notifications:
  email: github@jbzoo.com
